---
- hosts: all 
  become: true
  tasks:
  - name: Install nginx
    yum: 
       name: "nginx" 
       state: "latest"
  - name: Start and enable service nginx 
    service:
       name: nginx 
       state: started
       enabled: true 
  - name: Copy
    copy:  
       src: index.html
       dest: /root/jenkins-Q4/usr/share/nginx/html/ 
         
         
